### ISSUE TITLE
Issue with router.post

### ISSUE THREAD

**Issue by ghost** [polcham/mongoose-express-ts#1]
![image](https://user-images.githubusercontent.com/7788760/81061613-48a19400-8ef2-11ea-8d5f-1f001180680f.png)
getting this usse while running the app

**Comment by qlkvg** [comment]
I met the same issue, and removing inner square brackets in `handlers` of router.post helped. I am completely new to node.js and have now idea, why it helped tho :D

**Comment by polcham** [comment]
Fixed on the latest commit. Thanks for the report @wavemeetu, @qlkvg great job!

**Comment by ghost** [comment]
Can you just brief about the issue, what was it and why. Just to better understand this code.
