### ISSUE TITLE
Found 154 errors

### ISSUE THREAD

**Issue by andriyfm** [polcham/mongoose-express-ts#2]
I have 154 errors when run `npm run tsc` at the first time.

I like this repo btw, so simple and easy to manage. Thanks

**Comment by polcham** [comment]
> I have 154 errors when run `npm run tsc` at the first time.
> 
> I like this repo btw, so simple and easy to manage. Thanks

This could be due to new packages, having breaking changes.

Can you attach a screenshot of the error, including the version of the packages that you're using. I will update this repo with the latest packages once I have more free time on my end.

**Comment by andriyfm** [comment]
package.json
```
{
    "dependencies": {
    "bcryptjs": "^2.4.3",
    "config": "^3.1.0",
    "express": "^4.16.4",
    "express-validator": "^5.3.1",
    "gravatar": "^1.8.0",
    "http-status-codes": "^1.3.2",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^5.5.7",
    "request": "^2.88.0",
    "typescript": "^3.4.5"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.2",
    "@types/config": "0.0.34",
    "@types/express": "^4.16.1",
    "@types/gravatar": "^1.8.0",
    "@types/mongoose": "^5.10.2",
    "@types/jsonwebtoken": "^8.3.2",
    "@types/node": "^14.14.10",
    "concurrently": "^5.3.0",
    "nodemon": "^1.19.0"
  }
}
```

error found after `npm run tsc`

![screenshoot](https://i.ibb.co/p4T897B/Screenshot-2020-12-13-062133.png)

**Comment by Ito170** [comment]
Try removing "@types/mongoose": "^5.10.2" from devDependencies and use the standard typing in mongoose 5.11. I believe there is a typing conflict between the two versions: 
https://stackoverflow.com/questions/65097317/errors-while-initializing-mongodb-with-nestjs-angular

Alternatively you can downgrade mongoose to a 5.10 version.

**Comment by andriyfm** [comment]
> Try removing "@types/mongoose": "^5.10.2" from devDependencies and use the standard typing in mongoose 5.11. I believe there is a typing conflict between the two versions:
> https://stackoverflow.com/questions/65097317/errors-while-initializing-mongodb-with-nestjs-angular
> 
> Alternatively you can downgrade mongoose to a 5.10 version.

Thanks, @Ito170 all works

**Comment by I-keep-trying** [comment]
Great repo I agree. 

However, I am continuing to have problems getting it to compile, even after removing @types/mongoose and updating to mongoose version 5.11.15. 


![Untitled](https://user-images.githubusercontent.com/26046173/107581971-d2d80080-6bc6-11eb-881e-80f4a77b80a0.png)


Also, I cannot figure out where to call `process.env.MONGODB_URI` since I prefer using a .gitignore'd .env to keep my db config variables. I don't know how to use the 'config' package and I don't really want to use it.

**Comment by Ito170** [comment]
This one I ran into as well. I'm not sure why it's a problem and don't understand why this solution works, but it does. 

Replace the Profile declaration under models => Profile.ts:

![image](https://user-images.githubusercontent.com/20607905/107730775-3e52c880-6cc2-11eb-9613-b9a9b6f233c3.png)

and the User declaration under models => User.ts:

![image](https://user-images.githubusercontent.com/20607905/107730747-309d4300-6cc2-11eb-9561-31e100ee3407.png)

Edit: you will need to replace the Model from the mongoose import with model.

As for the environment variables, you can use the dotenv package (or dotenv-flow if you want to use .env.production and .env.development) here is a link to their npm page: https://www.npmjs.com/package/dotenv and https://www.npmjs.com/package/dotenv-flow

Config package gets variables using config.get("YOUR VARIABLE NAME HERE"), where the environment variables are set under the config folder in default.json. https://www.npmjs.com/package/config

**Comment by I-keep-trying** [comment]
@Ito170 
> Replace the Profile declaration


Wow thank you so much! That did the trick! I'm not proficient with typescript yet so... yeah. 

Re: environment variables/config - I do appreciate the tips, but I was not confused about ::how:: to use the config package, or dotenv, I just saw the mongodb uri in that json file and it threw me. If you gitignore `default.json`, how would you build and publish to heroku for example? Because the way `database.ts` calls `config.get`, it won't work without that json file, and I don't ::think:: you can add an entire json file to heroku config, can you?

**Comment by Ito170** [comment]
Oh sorry I see what you are asking now, I would say that is a bit outside of the scope of this issue thread.

But how I have done it (which may not be the best way, but it works), is using Nodemon to set the development environment variables. Whenever the code is run using Nodemon these variables are loaded into process.env.YOUR_VARIABLE. The nodemon.json would look something like this:

```
{
  "env": {
      "YOUR_VARIABLE": "YOUR_VALUE"
  }
}
```

This would require removing config from the project and changing any variables to point to the process.env. Now when you deploy it to Heroku you can set the production environment variables under the project settings in this section:

![image](https://user-images.githubusercontent.com/20607905/110157849-ade64000-7db6-11eb-9355-abde983417ed.png)

That way they are loaded into process.env when the app deploys.

Hope that helps!

EDIT: Be sure to add the nodemon.json file to your .gitignore!

**Comment by I-keep-trying** [comment]
OK thanks! I have never used nodemon for handling environment variables before, so this is all new to me. Sorry for derailing the issue, it's a user problem, not the repo.

**Comment by polcham** [comment]
I updated the syntax to match the updated packages, thanks. This is now closed.
